Repository Next3ru/Next3ru_Frontend, pull requests merged in 2024-07, with the labels that each got.

#43 [feture]NavBar 퍼블리싱 80% 완료
  public/images/navbar/SubLogo.svg
  src/app/(home)/(pages)/layout.tsx
  src/components/NavBar.tsx
  src/components/NavBarSub.tsx
  src/styles/jaemin.css
Labels: 🎨 Publising

#64 58 오늘의 선수 api 연동
  package-lock.json
  package.json
  public/images/hitter/강민성.svg
  public/images/hitter/강백호.svg
  public/images/hitter/강현우.svg
  public/images/hitter/김건형.svg
  public/images/hitter/김민석.svg
  public/images/hitter/김민혁.svg
  public/images/hitter/김병준.svg
  public/images/hitter/김상수.svg
  public/images/hitter/김준태.svg
  public/images/hitter/로하스.svg
  public/images/hitter/문상철.svg
  public/images/hitter/박경수.svg
  public/images/hitter/박민석.svg
  public/images/hitter/배정대.svg
  public/images/hitter/송민섭.svg
  public/images/hitter/신본기.svg
  public/images/hitter/안치영.svg
  public/images/hitter/안현민.svg
  public/images/hitter/오윤석.svg
  public/images/hitter/오재일.svg
  public/images/hitter/윤준혁.svg
  public/images/hitter/이호연.svg
  public/images/hitter/장성우.svg
  public/images/hitter/장준원.svg
  public/images/hitter/정준영.svg
  public/images/hitter/조대현.svg
  public/images/hitter/조용호.svg
  public/images/hitter/천성호.svg
  public/images/hitter/홍현빈.svg
  public/images/hitter/황재균.svg
  public/images/구름.svg
  public/images/비.svg
  src/app/(home)/(pages)/layout.tsx
  src/app/(home)/(pages)/today-player/page.tsx
  src/components/chungwoo/PlayerCard.tsx
  src/components/chungwoo/PlayerList.tsx
  src/components/chungwoo/TodayPlayerCon.tsx
  src/components/chungwoo/TodayPlayerHitterModal.tsx
  src/components/chungwoo/TodayPlayerPitcherModal.tsx
  src/store/Today-player.tsx
Labels: ✨ Feature, 📬 API

#67 [feat]NavBar 및 서브메뉴 기능구현 ,퍼블리싱 완료
  package-lock.json
  package.json
  src/components/NavBar.tsx
  src/components/NavBarSub.tsx
  src/styles/globals.css
  src/styles/jaemin.css
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Publising, 🥰 Accessibility

#68 60 투수페이지 api 연동
  next.config.mjs
  package-lock.json
  package.json
  public/images/logo2.png
  src/app/(home)/(pages)/player/pitcher/page.tsx
  src/components/chungwoo/PitcherDashBoard.tsx
  src/components/chungwoo/PlayerPitcher.tsx
  src/components/chungwoo/TodayPlayerCon.tsx
  src/store/PitcherDashBoard.tsx
  src/store/PlayerPitcher.tsx
  src/store/Today-player.tsx
  tailwind.config.ts
Labels: 🎨 Publising

#71 style : 챗봇 UI 컴포넌트 추가 및 merge
  package-lock.json
  package.json
  src/app/chatbot/layout.tsx
  src/app/chatbot/page.tsx
  src/app/globals.css
  src/components/gwanwoo/chatbot/ChatHeader.tsx
  src/components/gwanwoo/chatbot/ChatHeaderFlex.tsx
  src/components/gwanwoo/chatbot/EmptyState.tsx
  src/components/gwanwoo/chatbot/InitialSetting.tsx
  src/components/gwanwoo/chatbot/MainBoard.tsx
  src/components/gwanwoo/chatbot/MessageInput.tsx
  src/components/gwanwoo/chatbot/ModalComponent.tsx
  src/components/gwanwoo/chatbot/SendButton.tsx
  src/components/gwanwoo/chatbot/Speeddial.tsx
  src/components/gwanwoo/chatbot/bot/config.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Options.tsx
  tailwind.config.ts
Labels: 🎨 Publising

#72 fix: package.json 오류수정 , layout 주석처리
  package.json
  src/app/(home)/(pages)/layout.tsx
Labels: 🐞 BugFix

#74 chore: 필요없어진 컴포넌트들 삭제
  package-lock.json
  public/images/chatbot/Kt Wiz.svg
  src/components/gwanwoo/chatbot/ModalComponent.tsx
  src/components/gwanwoo/chatbot/MyModalComponent.tsx
  src/components/gwanwoo/chatbot/Speeddial.tsx
  src/components/gwanwoo/chatbot/bot/MessageParser.tsx
  src/components/gwanwoo/chatbot/bot/widgets/DailySchedule.tsx
  src/components/gwanwoo/chatbot/bot/widgets/FavoritePlayer.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Options.tsx
  src/components/gwanwoo/chatbot/bot/widgets/TeamRecord.tsx
Labels: 🎨 Publising

#75 73 챗봇 api 연동
  src/app/(home)/layout.tsx
  src/app/chatbot/page.tsx
  src/components/gwanwoo/chatbot/Chatting.tsx
  src/components/gwanwoo/chatbot/bot/MessageParser.tsx
  src/components/gwanwoo/chatbot/bot/config.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Overview.tsx
  src/store/ChatBot.tsx
  src/styles/gwanwoo.css
Labels: 📬 API

#77 feat: AI 스쿼드 DashBoard 제작 & NavBar 수정
  public/images/WinningKt.svg
  src/app/(home)/layout.tsx
  src/components/NavBar.tsx
  src/components/NavBarSub.tsx
  src/components/jaemin/AiModal.tsx
  src/components/jaemin/DroppedCard.tsx
  src/components/jaemin/PlayerCard.tsx
  src/components/jaemin/SquardPlayerCon.tsx
  src/store/SquardPitcher.tsx
  src/store/Today-player.tsx
Labels: ✨ Feature, 🎨 Publising

#78 feat: swiper 기능 추가 외 1건
  package-lock.json
  package.json
  src/app/chatbot/page.tsx
  src/components/gwanwoo/chatbot/ChatMessage.tsx
  src/components/gwanwoo/chatbot/Chatting.tsx
  src/components/gwanwoo/chatbot/DailySchedule copy.tsx
  src/components/gwanwoo/chatbot/KTBotAvatar.tsx
  src/components/gwanwoo/chatbot/bot/config.tsx
  src/components/gwanwoo/chatbot/bot/widgets/DailySchedule.tsx
  src/components/gwanwoo/chatbot/bot/widgets/FavoritePlayer/BatterFavoritePlayer.tsx
  src/components/gwanwoo/chatbot/bot/widgets/FavoritePlayer/PitcherFavoritePlayer.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Options.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Swiper.tsx
  src/components/gwanwoo/chatbot/bot/widgets/TeamRecord.tsx
  src/styles/gwanwoo.css
Labels: ✨ Feature

#79 feat: 챗봇 API 연동 및 UI 수정
  public/images/cloudy.svg
  public/images/day.svg
  public/images/rainy-6.svg
  src/app/(home)/(pages)/player/pitcher/page.tsx
  src/app/(home)/layout.tsx
  src/app/chatbot/page.tsx
  src/components/chungwoo/PitcherDashBoard.tsx
  src/components/chungwoo/PlayerPitcher.tsx
  src/components/chungwoo/TodayPlayerCon.tsx
  src/components/gwanwoo/chatbot/bot/ActionProvider.tsx
  src/components/gwanwoo/chatbot/bot/widgets/DailySchedule.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Overview.tsx
  src/components/gwanwoo/chatbot/bot/widgets/TeamRecord.tsx
  src/store/ChatBot.tsx
Labels: ✨ Feature, 📬 API

#80 feat: TodayLineUp 컴포넌트 생성
  src/components/gwanwoo/chatbot/bot/ActionProvider.tsx
  src/components/gwanwoo/chatbot/bot/MessageParser.tsx
  src/components/gwanwoo/chatbot/bot/config.tsx
  src/components/gwanwoo/chatbot/bot/widgets/DailySchedule.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Overview.tsx
  src/components/gwanwoo/chatbot/bot/widgets/TeamRecord.tsx
  src/components/gwanwoo/chatbot/bot/widgets/TodayLineUp.tsx
  src/styles/gwanwoo.css
Labels: ✨ Feature

#81 add: 각 구단 로고 파일 모은 폴더 추가
  public/images/chatbot/logos/emblem_Doosan.png
  public/images/chatbot/logos/emblem_Hanhwa.png
  public/images/chatbot/logos/emblem_KT.png
  public/images/chatbot/logos/emblem_Kia.png
  public/images/chatbot/logos/emblem_Kiwoom.png
  public/images/chatbot/logos/emblem_LG.png
  public/images/chatbot/logos/emblem_Lotte.png
  public/images/chatbot/logos/emblem_NC.png
  public/images/chatbot/logos/emblem_SK.png
  public/images/chatbot/logos/emblem_Samsung.png
  src/app/chatbot/page.tsx
  src/components/gwanwoo/chatbot/bot/widgets/DailySchedule.tsx
Labels: 🎨 Publising

#82 feat: 멘토님 보고 전 디테일한 작업 마무리
  src/components/chungwoo/PitcherDashBoard.tsx
  src/components/chungwoo/PlayerCard.tsx
  src/components/chungwoo/PlayerPitcher.tsx
  src/components/chungwoo/TodayPlayerCon.tsx
  src/components/chungwoo/TodayPlayerHitterModal.tsx
  src/components/chungwoo/TodayPlayerPitcherModal.tsx
  src/components/gwanwoo/chatbot/bot/ActionProvider.tsx
  src/components/gwanwoo/chatbot/bot/widgets/DailySchedule.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Options.tsx
  src/components/gwanwoo/chatbot/bot/widgets/Overview.tsx
  src/components/gwanwoo/chatbot/bot/widgets/TeamRecord.tsx
  src/components/gwanwoo/chatbot/bot/widgets/TodayLineUp.tsx
  src/store/ChatBot.tsx
  src/store/PlayerPitcher.tsx
  src/store/Today-player.tsx
Labels: ✨ Feature, 🎨 Publising, 📬 API

#84 api: ai dashboard api 연동 & dashboard 기능 구현
  package-lock.json
  package.json
  public/images/pitcher/이채호.svg
  src/components/jaemin/AiModal.tsx
  src/components/jaemin/DroppedCard.tsx
  src/components/jaemin/PlayerCard.tsx
  src/components/jaemin/SquardPlayerCon.tsx
  src/store/SquardPitcher.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Publising, 📬 API

#89 73 챗봇 api 연동
  package-lock.json
  public/images/chatbot/logos/emblem_두산.png
  public/images/chatbot/logos/emblem_롯데.png
  public/images/chatbot/logos/emblem_삼성.png
  public/images/chatbot/logos/emblem_키움.png
  public/images/chatbot/logos/emblem_한화.png
  src/app/(home)/(pages)/reservasion/page.tsx
  src/app/(home)/layout.tsx
  src/components/chungwoo/PitcherDashBoard.tsx
  src/components/chungwoo/TicketReservation.tsx
  src/components/gwanwoo/chatbot/bot/ActionProvider.tsx
  src/components/gwanwoo/chatbot/bot/MessageParser.tsx
  src/store/ChatBot.tsx
  src/store/PitcherDashBoard.tsx
  src/store/TicketStore.tsx
Labels: 📬 API

#92 [fix] build시 에러 수정, 루트 디렉토리 변경
  package-lock.json
  src/app/(home)/(pages)/layout.tsx
  src/app/(home)/layout.tsx
  src/components/jaemin/AiModal.tsx
  src/components/jaemin/PlayerPitcher.tsx
  src/components/jaemin/Squard.tsx
  src/components/jaemin/SquardPlayerCon.tsx
Labels: ✨ Feature, 🐞 BugFix

#93 WIP: 1ecc4ee Merge pull request #89 from Next3ru/73-챗봇-api-연동 및 투수상세페…
  src/components/chungwoo/PitcherDashBoard.tsx
  src/components/chungwoo/PlayerPitcher.tsx
  src/components/elisa/MultiFileDropzone.tsx
  src/components/gwanwoo/chatbot/bot/widgets/DailySchedule.tsx
  src/styles/cheongwoo.css
  tailwind.config.ts
Labels: 🎨 Publising
